services:
  - type: web
    name: contact-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
